INSERT INTO Building (btype, price) VALUES ('Apartment', 50.00);
INSERT INTO Building (btype, price) VALUES ('House', 70.00);
INSERT INTO Building (btype, price) VALUES ('Cabin', 70.00);
INSERT INTO Building (btype, price) VALUES ('Bed & Breakfast', 70.00);
INSERT INTO Building (btype, price) VALUES ('Camper/RV', 70.00);
INSERT INTO Building (btype, price) VALUES ('Boat', 70.00);
INSERT INTO Building (btype, price) VALUES ('Mansion', 100.00);

INSERT INTO Amenity (atype, category, price) VALUES ('Wifi', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('TV', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Kitchen', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Washer', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('AC', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Free Parking', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Paid Parking', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Dedicated Workspace', 'Essential', 40.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Pool', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Hot Tub', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Patio', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Fire Pit', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Grill', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Outdoor dining', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Pool Table', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Indoor Fireplace', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Piano', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Exercise', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Lake Access', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Beach Access', 'Standout', 60.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Smoke Alarm', 'Safety', 1.00);
INSERT INTO Amenity (atype, category, price) VALUES ('First Aid Kit', 'Safety', 1.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Fire Extinguisher', 'Safety', 1.00);
INSERT INTO Amenity (atype, category, price) VALUES ('Carbon Monoxide Alarm', 'Safety', 1.00);
